### ISSUE TITLE
Dataset Request for Bangla-spam-sms classification

### ISSUE THREAD

**Issue by syeed111** [fahimvj/Bengali_SMS_Spam_using_ML_MC191010#1]
We are doing research on building a model for bangla-spam-sms classification which will be mobile friendly . We've got only one dataset on kaggle which has a few bangla sms . We will appriciate if you share your dataset through kaggle or directly to help us building a strong model . Thanks for your support .

**Comment by fahimvj** [comment]
I have uploaded here. Its an older version, trying to add some more data. Will upload later the latest dataset on the same link.


https://www.kaggle.com/datasets/fahimvj/bengali-sms-spam-detection-dataset/data

**Comment by syeed111** [comment]
@fahimvj  Thanks for your co-operation .Jajakallah Khairan .
